### PR TITLE
Bump version to 0.1.3

### PR DESCRIPTION
**Pull request by asinghvi17**
So we can get the provider fixes out

### CODE REVIEW

**Comment by rafaqz** [comment]
Hmm weird error

**Comment by asinghvi17** [comment]
That is strange...and specifically on 1.6.  1.9 and nightly seem fine somehow...

**Comment by rafaqz** [comment]
Oh hah I think its just new `replace` syntax

**Comment by rafaqz** [comment]
Its fixed on main now

**Pull request merged**
